apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}

  - name: MinIO
    type: prometheus
    access: proxy
    url: http://minio:9000
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "GET"
    secureJsonData: {}

  - name: Kafka
    type: prometheus
    access: proxy
    url: http://kafka:9101
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "GET"
    secureJsonData: {} 